#!/bin/bash
# Setup script for Archipelago Cowork Template
# Creates the full 307-directory company structure in the specified location.
#
# Usage:
#   ./setup.sh                    # Creates structure in current directory
#   ./setup.sh ~/my-company       # Creates structure in specified directory

TARGET="${1:-.}"

mkdir -p "$TARGET"

# Finance
mkdir -p "$TARGET/Finance/Financial Management/Billing"
mkdir -p "$TARGET/Finance/Financial Management/Financial Tooling"
mkdir -p "$TARGET/Finance/Financial Management/Organisational Performance/Liquidity"
mkdir -p "$TARGET/Finance/Financial Management/Organisational Performance/Project Performance"
mkdir -p "$TARGET/Finance/Financial Management/Organisational Performance/Setting Targets"
mkdir -p "$TARGET/Finance/Financial Management/Payments"
mkdir -p "$TARGET/Finance/Financial Management/Project Budgets"
mkdir -p "$TARGET/Finance/Financial Management/Taxes & Surcharges"
mkdir -p "$TARGET/Finance/Financial Strategy/Financing/Investments"
mkdir -p "$TARGET/Finance/Financial Strategy/Financing/Loans & Credit"
mkdir -p "$TARGET/Finance/Financial Strategy/Financing/Subsidies & Funds"
mkdir -p "$TARGET/Finance/Financial Strategy/Impact Analyses/Financial Prognoses"
mkdir -p "$TARGET/Finance/Financial Strategy/Impact Analyses/Investment Decisions"
mkdir -p "$TARGET/Finance/Financial Strategy/Impact Analyses/Risk Analyses"
mkdir -p "$TARGET/Finance/Financial Strategy/Reporting/Balance Sheet"
mkdir -p "$TARGET/Finance/Financial Strategy/Reporting/Company Budget"
mkdir -p "$TARGET/Finance/Financial Strategy/Reporting/Profit & Loss Statement"
mkdir -p "$TARGET/Finance/Financial Strategy/Reporting/Quarterly Figures"
mkdir -p "$TARGET/Finance/Financial Strategy/Research/Trends & Opportunities"
mkdir -p "$TARGET/Finance/Insurance"

# HRM
mkdir -p "$TARGET/HRM/Administrative Processes/Contract Management/Cars & Lease"
mkdir -p "$TARGET/HRM/Administrative Processes/Contract Management/Employee Contracts/Secondary Terms of Employment"
mkdir -p "$TARGET/HRM/Administrative Processes/Documentation/Key Register"
mkdir -p "$TARGET/HRM/Administrative Processes/Documentation/Vacations & Absenteeism"
mkdir -p "$TARGET/HRM/Administrative Processes/HR Communication"
mkdir -p "$TARGET/HRM/Administrative Processes/Health & Well-being/Lunch"
mkdir -p "$TARGET/HRM/Administrative Processes/Legal & Compliance/Data Management"
mkdir -p "$TARGET/HRM/Administrative Processes/Operational Safety/Ergonomics & Productivity"
mkdir -p "$TARGET/HRM/Administrative Processes/Operational Safety/IT Security"
mkdir -p "$TARGET/HRM/Administrative Processes/Operational Safety/Production Safety"
mkdir -p "$TARGET/HRM/Administrative Processes/Other"
mkdir -p "$TARGET/HRM/Administrative Processes/Payrolling/Tooling"
mkdir -p "$TARGET/HRM/Administrative Processes/Policy & Procedures/Employee Handbook/Employees"
mkdir -p "$TARGET/HRM/Administrative Processes/Policy & Procedures/Employee Handbook/Freelancers"
mkdir -p "$TARGET/HRM/Culture/Core Values"
mkdir -p "$TARGET/HRM/Culture/Spontaneous Surprises/Birthdays"
mkdir -p "$TARGET/HRM/Culture/Spontaneous Surprises/Official Holidays"
mkdir -p "$TARGET/HRM/Culture/Team Activities"
mkdir -p "$TARGET/HRM/Employee Engagement/Personal OKRs"
mkdir -p "$TARGET/HRM/Employee Engagement/Strategic Alignment"
mkdir -p "$TARGET/HRM/Learning & Development/Performance Management/360 Reviews"
mkdir -p "$TARGET/HRM/Learning & Development/Performance Management/Performance Review Meetings"
mkdir -p "$TARGET/HRM/Learning & Development/Performance Management/Team Retrospectives"
mkdir -p "$TARGET/HRM/Learning & Development/Training & Development/Development Leadership & Management"
mkdir -p "$TARGET/HRM/Learning & Development/Training & Development/L&D Activities"
mkdir -p "$TARGET/HRM/Learning & Development/Training & Development/L&D Budgets"
mkdir -p "$TARGET/HRM/Learning & Development/Training & Development/Personal Development Plans"
mkdir -p "$TARGET/HRM/Recruitment & Selection/Employer Brand"
mkdir -p "$TARGET/HRM/Recruitment & Selection/Hiring/Hiring Process/Tooling"
mkdir -p "$TARGET/HRM/Recruitment & Selection/Hiring/Selection Criteria/Assessments"
mkdir -p "$TARGET/HRM/Recruitment & Selection/Hiring/Selection Criteria/Interviews"
mkdir -p "$TARGET/HRM/Recruitment & Selection/Hiring/Selection Criteria/Tooling"
mkdir -p "$TARGET/HRM/Recruitment & Selection/On- and Offboarding/Checklist"
mkdir -p "$TARGET/HRM/Recruitment & Selection/On- and Offboarding/Documents"
mkdir -p "$TARGET/HRM/Recruitment & Selection/Recruitment/Channels/Events"
mkdir -p "$TARGET/HRM/Recruitment & Selection/Recruitment/Channels/Online"
mkdir -p "$TARGET/HRM/Recruitment & Selection/Recruitment/Channels/Partners"
mkdir -p "$TARGET/HRM/Recruitment & Selection/Recruitment/Documents & Templates"
mkdir -p "$TARGET/HRM/Recruitment & Selection/Recruitment/Talent Pool/Flexworkers/Students"
mkdir -p "$TARGET/HRM/Recruitment & Selection/Recruitment/Talent Pool/Flexworkers/Zero-hours"
mkdir -p "$TARGET/HRM/Recruitment & Selection/Recruitment/Talent Pool/Freelancers/Agreements"
mkdir -p "$TARGET/HRM/Recruitment & Selection/Recruitment/Talent Pool/Freelancers/Database"
mkdir -p "$TARGET/HRM/Recruitment & Selection/Recruitment/Talent Pool/Full-timers"
mkdir -p "$TARGET/HRM/Recruitment & Selection/Recruitment/Talent Pool/Other/Temporary Employment Agencies"
mkdir -p "$TARGET/HRM/Recruitment & Selection/Recruitment/Talent Pool/Universities/Internships"
mkdir -p "$TARGET/HRM/Talent Strategy/HR Roadmap/Career Planning"
mkdir -p "$TARGET/HRM/Talent Strategy/HR Roadmap/HR Demand Planning"
mkdir -p "$TARGET/HRM/Talent Strategy/HR Roadmap/Strategy-Talent Fit Gap Analysis"
mkdir -p "$TARGET/HRM/Talent Strategy/Organisational Chart/Clear Roles & Responsibilities"
mkdir -p "$TARGET/HRM/Talent Strategy/Research/Trends & Opportunities"

# Marketing & Communications
mkdir -p "$TARGET/Marketing & Communications/Brand Development/Brand Book"
mkdir -p "$TARGET/Marketing & Communications/Brand Development/Quality Control"
mkdir -p "$TARGET/Marketing & Communications/Brand Development/Templates"
mkdir -p "$TARGET/Marketing & Communications/Brand Strategy/Channels/Channels & Targets"
mkdir -p "$TARGET/Marketing & Communications/Brand Strategy/M&C Budget"
mkdir -p "$TARGET/Marketing & Communications/Brand Strategy/M&C Roadmap"
mkdir -p "$TARGET/Marketing & Communications/Brand Strategy/Message/Value Proposition"
mkdir -p "$TARGET/Marketing & Communications/Brand Strategy/Metrics"
mkdir -p "$TARGET/Marketing & Communications/Brand Strategy/Target Group/Customer Profiling"
mkdir -p "$TARGET/Marketing & Communications/Content Strategy/Ads & Promotion/Experiments"
mkdir -p "$TARGET/Marketing & Communications/Content Strategy/Ads & Promotion/Monitoring"
mkdir -p "$TARGET/Marketing & Communications/Content Strategy/M&C Tooling"
mkdir -p "$TARGET/Marketing & Communications/Content Strategy/Other Media/Awards & Competitions"
mkdir -p "$TARGET/Marketing & Communications/Content Strategy/Other Media/Magazines"
mkdir -p "$TARGET/Marketing & Communications/Content Strategy/Other Media/Newsletter"
mkdir -p "$TARGET/Marketing & Communications/Content Strategy/Other Media/Other/Influencers"
mkdir -p "$TARGET/Marketing & Communications/Content Strategy/Other Media/Other/Newspapers"
mkdir -p "$TARGET/Marketing & Communications/Content Strategy/Other Media/Other/Radio & TV"
mkdir -p "$TARGET/Marketing & Communications/Content Strategy/Other Media/Podcast"
mkdir -p "$TARGET/Marketing & Communications/Content Strategy/Social Media/Content Planning"
mkdir -p "$TARGET/Marketing & Communications/Content Strategy/Social Media/Content Realisation"
mkdir -p "$TARGET/Marketing & Communications/Content Strategy/Social Media/Growth Hacking & Trends"
mkdir -p "$TARGET/Marketing & Communications/Content Strategy/Social Media/Monitoring"
mkdir -p "$TARGET/Marketing & Communications/Content Strategy/Website/Content/Blogs"
mkdir -p "$TARGET/Marketing & Communications/Content Strategy/Website/Content/Content Planning"
mkdir -p "$TARGET/Marketing & Communications/Content Strategy/Website/Content/Customer References"
mkdir -p "$TARGET/Marketing & Communications/Content Strategy/Website/Content/General"
mkdir -p "$TARGET/Marketing & Communications/Content Strategy/Website/Content/Project Descriptions"
mkdir -p "$TARGET/Marketing & Communications/Content Strategy/Website/Conversion Optimisation"
mkdir -p "$TARGET/Marketing & Communications/Content Strategy/Website/Design"
mkdir -p "$TARGET/Marketing & Communications/Content Strategy/Website/Monitoring"
mkdir -p "$TARGET/Marketing & Communications/Content Strategy/Website/SEO"
mkdir -p "$TARGET/Marketing & Communications/Media/Image Database"
mkdir -p "$TARGET/Marketing & Communications/Media/Media Waivers"
mkdir -p "$TARGET/Marketing & Communications/PR/Account Management"
mkdir -p "$TARGET/Marketing & Communications/PR/Content"
mkdir -p "$TARGET/Marketing & Communications/PR/Press Database"
mkdir -p "$TARGET/Marketing & Communications/Product & Service Marketing/General M&C Strategy"
mkdir -p "$TARGET/Marketing & Communications/Promotions & Events/Events"
mkdir -p "$TARGET/Marketing & Communications/Promotions & Events/Webinars"

# Operations
mkdir -p "$TARGET/Operations/Legal & Compliance/Customer Contracts"
mkdir -p "$TARGET/Operations/Legal & Compliance/Documentation"
mkdir -p "$TARGET/Operations/Legal & Compliance/Terms & Conditions"
mkdir -p "$TARGET/Operations/Operational Strategy/Operations Roadmap/Process Innovation & Scaling"
mkdir -p "$TARGET/Operations/Operational Strategy/Research/Trends & Opportunities"
mkdir -p "$TARGET/Operations/Planning/Resource Planning/People"
mkdir -p "$TARGET/Operations/Planning/Resource Planning/Projects"
mkdir -p "$TARGET/Operations/Planning/Resource Planning/Tooling"
mkdir -p "$TARGET/Operations/Process/Documentation"
mkdir -p "$TARGET/Operations/Process/Milestones & Metrics"
mkdir -p "$TARGET/Operations/Process/Operational Meetings/Daily Standup"
mkdir -p "$TARGET/Operations/Process/Operational Meetings/Weekly"
mkdir -p "$TARGET/Operations/Process/Phased Development Process"
mkdir -p "$TARGET/Operations/Process/Quality Control"
mkdir -p "$TARGET/Operations/Process/Time Tracking"
mkdir -p "$TARGET/Operations/Process/Tooling & Automation"
mkdir -p "$TARGET/Operations/Projects/Assembling Project Teams"
mkdir -p "$TARGET/Operations/Projects/Project Budget"
mkdir -p "$TARGET/Operations/Projects/Supervision/Progress on Milestones & Metrics"
mkdir -p "$TARGET/Operations/Projects/Supervision/Project Results"
mkdir -p "$TARGET/Operations/Projects/Supervision/Quality Control"
mkdir -p "$TARGET/Operations/Suppliers/Account Management"
mkdir -p "$TARGET/Operations/Suppliers/Documentation"
mkdir -p "$TARGET/Operations/Suppliers/Supplier Database"
mkdir -p "$TARGET/Operations/Workplace/Office Improvements"
mkdir -p "$TARGET/Operations/Workplace/Office Management/Administration"
mkdir -p "$TARGET/Operations/Workplace/Office Management/Front Desk"
mkdir -p "$TARGET/Operations/Workplace/Office Management/Office Supplies"
mkdir -p "$TARGET/Operations/Workplace/Tooling & Equipment"
mkdir -p "$TARGET/Operations/Workplace/Workshop Improvements"

# Products & Services
mkdir -p "$TARGET/Products & Services/IT & Tech Stack"
mkdir -p "$TARGET/Products & Services/Innovation & R&D"
mkdir -p "$TARGET/Products & Services/Knowledge Database"
mkdir -p "$TARGET/Products & Services/Product & Portfolio Strategy"
mkdir -p "$TARGET/Products & Services/Service Contracts"
mkdir -p "$TARGET/Products & Services/Tailor-made Tasks"

# Sales & Business Development
mkdir -p "$TARGET/Sales & Business Development/Business Development/Business Modelling/Business Case"
mkdir -p "$TARGET/Sales & Business Development/Business Development/Customer & Partner Identification"
mkdir -p "$TARGET/Sales & Business Development/Business Development/Product & Service Development/Existing Product New Market"
mkdir -p "$TARGET/Sales & Business Development/Business Development/Product & Service Development/New Market New Product"
mkdir -p "$TARGET/Sales & Business Development/Business Development/Product & Service Development/New Product Existing Market"
mkdir -p "$TARGET/Sales & Business Development/Business Development/Proposals & Buy-in"
mkdir -p "$TARGET/Sales & Business Development/Business Development/Research/Competitor Analysis"
mkdir -p "$TARGET/Sales & Business Development/Business Development/Research/Customer Needs"
mkdir -p "$TARGET/Sales & Business Development/Business Development/Research/Market Trends"
mkdir -p "$TARGET/Sales & Business Development/Commercial Strategy/Market Research/Competitor Analyses"
mkdir -p "$TARGET/Sales & Business Development/Commercial Strategy/Market Research/Trends & Opportunities"
mkdir -p "$TARGET/Sales & Business Development/Commercial Strategy/Reporting/CAQ"
mkdir -p "$TARGET/Sales & Business Development/Commercial Strategy/Reporting/Conversion"
mkdir -p "$TARGET/Sales & Business Development/Commercial Strategy/Reporting/Retention"
mkdir -p "$TARGET/Sales & Business Development/Commercial Strategy/Sales Channels"
mkdir -p "$TARGET/Sales & Business Development/Commercial Strategy/Sales Offering/Price Points"
mkdir -p "$TARGET/Sales & Business Development/Commercial Strategy/Sales Offering/Target Group"
mkdir -p "$TARGET/Sales & Business Development/Commercial Strategy/Sales Offering/Value Proposition"
mkdir -p "$TARGET/Sales & Business Development/Commercial Strategy/Sales Strategies"
mkdir -p "$TARGET/Sales & Business Development/Commercial Strategy/Sales Targets"
mkdir -p "$TARGET/Sales & Business Development/Customer Relations/Account Management/Exploring Needs"
mkdir -p "$TARGET/Sales & Business Development/Customer Relations/Account Management/Product Updates"
mkdir -p "$TARGET/Sales & Business Development/Customer Relations/Account Management/Tokens of Appreciation"
mkdir -p "$TARGET/Sales & Business Development/Customer Relations/Project Evaluation & References"
mkdir -p "$TARGET/Sales & Business Development/Customer Relations/Recurring Sales"
mkdir -p "$TARGET/Sales & Business Development/Events & Socials/Fairs"
mkdir -p "$TARGET/Sales & Business Development/Events & Socials/Networking Events"
mkdir -p "$TARGET/Sales & Business Development/Sales Operations/Administrative Tasks/CRM"
mkdir -p "$TARGET/Sales & Business Development/Sales Operations/Administrative Tasks/Contracts"
mkdir -p "$TARGET/Sales & Business Development/Sales Operations/Email & Follow-up"
mkdir -p "$TARGET/Sales & Business Development/Sales Operations/Hand-over to Project Teams"
mkdir -p "$TARGET/Sales & Business Development/Sales Operations/Lead Generation/Cold Calling"
mkdir -p "$TARGET/Sales & Business Development/Sales Operations/Meetings/Calls"
mkdir -p "$TARGET/Sales & Business Development/Sales Operations/Meetings/Face-to-face"
mkdir -p "$TARGET/Sales & Business Development/Sales Operations/Quotations"
mkdir -p "$TARGET/Sales & Business Development/Sales Process/CRM System/Monitoring"
mkdir -p "$TARGET/Sales & Business Development/Sales Process/CRM System/Pipelines & Protocol"
mkdir -p "$TARGET/Sales & Business Development/Sales Process/Sales Process Handbook"
mkdir -p "$TARGET/Sales & Business Development/Sales Process/Supervision/Quality Control"
mkdir -p "$TARGET/Sales & Business Development/Sales Process/Supervision/Training"
mkdir -p "$TARGET/Sales & Business Development/Sales Process/Templates/General Sales Deck"
mkdir -p "$TARGET/Sales & Business Development/Sales Process/Templates/Product One-Pagers"
mkdir -p "$TARGET/Sales & Business Development/Sales Process/Templates/Quotation Templates"
mkdir -p "$TARGET/Sales & Business Development/Strategic Partner Network/Business Development Partners"
mkdir -p "$TARGET/Sales & Business Development/Strategic Partner Network/Expertise Partners"
mkdir -p "$TARGET/Sales & Business Development/Strategic Partner Network/Financing Partners/Funds"
mkdir -p "$TARGET/Sales & Business Development/Strategic Partner Network/Financing Partners/Government Institutions"
mkdir -p "$TARGET/Sales & Business Development/Strategic Partner Network/Financing Partners/Subsidies"
mkdir -p "$TARGET/Sales & Business Development/Strategic Partner Network/Network of Resellers"
mkdir -p "$TARGET/Sales & Business Development/Strategic Partner Network/Partner Events & Meetings"

# Strategy & Management
mkdir -p "$TARGET/Strategy & Management/Advisors/Board of Advisors"
mkdir -p "$TARGET/Strategy & Management/Advisors/External Coaching"
mkdir -p "$TARGET/Strategy & Management/Daily Management/Management Meetings"
mkdir -p "$TARGET/Strategy & Management/Daily Management/Shareholder Meetings"
mkdir -p "$TARGET/Strategy & Management/Long Term Strategy/Goals"
mkdir -p "$TARGET/Strategy & Management/Long Term Strategy/Mission"
mkdir -p "$TARGET/Strategy & Management/Long Term Strategy/Vision"
mkdir -p "$TARGET/Strategy & Management/Short Term Strategy/Business Model"
mkdir -p "$TARGET/Strategy & Management/Short Term Strategy/Objectives & Key Results"
mkdir -p "$TARGET/Strategy & Management/Short Term Strategy/Strategic Focus Areas"
mkdir -p "$TARGET/Strategy & Management/Short Term Strategy/Strategy Meetings"

echo "Created 307 directories in: $TARGET"
